### ISSUE TITLE
TypeError: Cannot read property 'getConnectionString' of undefined

### ISSUE THREAD

**Issue by ojongerius** [vladgolubev/jest-mongodb#3]
Hey there!

If I pull down your repo and npm install like so:

```sh
git clone git@github.com:vladgolubev/jest-mongodb.git && cd jest-mongodb
npm install
```

Running Jest will fail like so:

```sh
▶ jest

 RUNS  ./mongo-insert.test.js
 FAIL  ./mongo-aggregate.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'getConnectionString' of undefined

       9 |     console.log('Setup MongoDB Test Environment');
      10 |
    > 11 |     this.global.__MONGO_URI__ = await global.__MONGOD__.getConnectionString();
      12 |     this.global.__MONGO_DB_NAME__ = global.__MONGO_DB_NAME__;
      13 |
      14 |     await super.setup();

      at MongoEnvironment.setup (mongo-environment.js:11:57)

 FAIL  ./mongo-insert.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'getConnectionString' of undefined

       9 |     console.log('Setup MongoDB Test Environment');
      10 |
    > 11 |     this.global.__MONGO_URI__ = await global.__MONGOD__.getConnectionString();
      12 |     this.global.__MONGO_DB_NAME__ = global.__MONGO_DB_NAME__;
      13 |
      14 |     await super.setup();

      at MongoEnvironment.setup (mongo-environment.js:11:57)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.409s
Ran all test suites.
Teardown mongod
```
If I run with --runInBand  will succeed:

```sh
▶ jest --runInBand
Setup MongoDB Test Environment
 PASS  ./mongo-insert.test.js
Teardown MongoDB Test Environment
Setup MongoDB Test Environment
 PASS  ./mongo-aggregate.test.js

Test Suites: 2 passed, 2 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        1.504s
Ran all test suites.
Teardown mongod
Teardown MongoDB Test Environment
```

And Jest runs that use the cache will succeed to *unless* you either manually remove the cache or pass --no-cache, ie:

```sh
▶ jest
Setup MongoDB Test Environment
 PASS  ./mongo-insert.test.js
Teardown MongoDB Test Environment
Setup MongoDB Test Environment
 PASS  ./mongo-aggregate.test.js

Test Suites: 2 passed, 2 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        1.089s
Ran all test suites.
Teardown mongod
Teardown MongoDB Test Environment

~/jest-mongodb  master ✗                                                                                        68d ⚑
▶ jest --no-cache

 RUNS  ./mongo-insert.test.js
 FAIL  ./mongo-insert.test.js.js
  ● Test suite failed to run

    TypeError: Cannot read property 'getConnectionString' of undefined

       9 |     console.log('Setup MongoDB Test Environment');
      10 |
    > 11 |     this.global.__MONGO_URI__ = await global.__MONGOD__.getConnectionString();
      12 |     this.global.__MONGO_DB_NAME__ = global.__MONGO_DB_NAME__;
      13 |
      14 |     await super.setup();

      at MongoEnvironment.setup (mongo-environment.js:11:57)

 FAIL  ./mongo-aggregate.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'getConnectionString' of undefined

       9 |     console.log('Setup MongoDB Test Environment');
      10 |
    > 11 |     this.global.__MONGO_URI__ = await global.__MONGOD__.getConnectionString();
      12 |     this.global.__MONGO_DB_NAME__ = global.__MONGO_DB_NAME__;
      13 |
      14 |     await super.setup();

      at MongoEnvironment.setup (mongo-environment.js:11:57)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.44s
Ran all test suites.
Teardown mongod
```

**Comment by ojongerius** [comment]
Aha! You judging by your `package.json` you do run `jest --runInBand` https://github.com/vladgolubev/jest-mongodb/blob/4b31ee4e4c40c6d939ba4791ff971050bfd92219/package.json#L18

Shall I resurrect #2 ? I'd still like to understand why this is happening 😀

**Comment by ojongerius** [comment]
I've raised https://github.com/facebook/jest/issues/6063 and created https://github.com/ojongerius/jest-bug to make it easier for the Jest folks to validate this happens against recent versions of all the things.

**Comment by vladgolubev** [comment]
@ojongerius I just updated `jest` and `mongodb` to the latest versions + removed `--runInBand` flag. This should work much more reliably now ✨
